apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: chenyulin015/examplevotingapp:result_beta_0.0
        name: result
        ports:
        - containerPort: 8080
          name: result
