apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: chenyulin015/examplevotingapp:vote_beta_0.0
        name: vote
        ports:
        - containerPort: 8080
          name: vote
